// Command demo seeds a running Redis-compatible server (Valkey/Redis) with
// representative asynq workloads and prints real queue statistics.
//
// It is the canonical seed/demo data source for docs/manual and docs/review:
// every number shown in those documents can be regenerated by running:
//
//	go run ./docs/manual/demo -redis_addr=localhost:16381
//
// The program exercises the real public API of this fork
// (github.com/austinyuch/asynq): Client enqueue across weighted queues,
// scheduled tasks, unique tasks, retry/archive flow, a worker Server with
// a ServeMux, and Inspector statistics.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"sort"
	"time"

	"github.com/austinyuch/asynq"
)

var redisAddr = flag.String("redis_addr", "localhost:6379", "redis/valkey address to seed")

const demoDB = 13 // keep clear of the test suite's default DB 14

type emailPayload struct {
	UserID int    `json:"user_id"`
	Locale string `json:"locale"`
}

type imagePayload struct {
	SrcURL string `json:"src_url"`
	Width  int    `json:"width"`
}

func main() {
	flag.Parse()
	opt := asynq.RedisClientOpt{Addr: *redisAddr, DB: demoDB}

	// Start from a clean slate so output is reproducible.
	flushDemoDB(opt)

	client := asynq.NewClient(opt)
	defer client.Close()

	fmt.Println("== 1. Enqueue real workloads =====================================")
	enqueue := func(task *asynq.Task, opts ...asynq.Option) {
		info, err := client.Enqueue(task, opts...)
		if err != nil {
			log.Fatalf("enqueue %s: %v", task.Type(), err)
		}
		fmt.Printf("  enqueued id=%s type=%-16s queue=%-8s state=%s\n",
			info.ID[:8], info.Type, info.Queue, info.State)
	}

	for i := 1; i <= 3; i++ {
		p, _ := json.Marshal(emailPayload{UserID: 1000 + i, Locale: "zh-TW"})
		enqueue(asynq.NewTask("email:welcome", p), asynq.Queue("critical"))
	}
	for _, w := range []int{640, 1280} {
		p, _ := json.Marshal(imagePayload{SrcURL: "s3://demo-bucket/cat.png", Width: w})
		enqueue(asynq.NewTask("image:resize", p), asynq.Queue("default"), asynq.MaxRetry(3))
	}
	// Scheduled: stays in "scheduled" state for the stats snapshot.
	enqueue(asynq.NewTask("report:generate", []byte(`{"period":"2026-06"}`)),
		asynq.Queue("low"), asynq.ProcessIn(2*time.Hour))
	// Unique: second enqueue within TTL must be rejected.
	enqueue(asynq.NewTask("cleanup:tmp", nil), asynq.Queue("low"), asynq.Unique(time.Hour))
	if _, err := client.Enqueue(asynq.NewTask("cleanup:tmp", nil),
		asynq.Queue("low"), asynq.Unique(time.Hour)); err != nil {
		fmt.Printf("  duplicate rejected: cleanup:tmp -> %v\n", err)
	}
	// Failing task: MaxRetry(0) archives it on first failure.
	enqueue(asynq.NewTask("billing:charge", []byte(`{"invoice":"INV-042"}`)),
		asynq.Queue("critical"), asynq.MaxRetry(0))

	fmt.Println()
	fmt.Println("== 2. Process with a real worker Server =========================")
	srv := asynq.NewServer(opt, asynq.Config{
		Concurrency: 4,
		Queues:      map[string]int{"critical": 6, "default": 3, "low": 1},
		LogLevel:    asynq.FatalLevel, // keep demo output deterministic
	})
	mux := asynq.NewServeMux()
	mux.HandleFunc("email:welcome", func(ctx context.Context, t *asynq.Task) error {
		var p emailPayload
		_ = json.Unmarshal(t.Payload(), &p)
		fmt.Printf("  processed email:welcome  user=%d locale=%s\n", p.UserID, p.Locale)
		return nil
	})
	mux.HandleFunc("image:resize", func(ctx context.Context, t *asynq.Task) error {
		var p imagePayload
		_ = json.Unmarshal(t.Payload(), &p)
		fmt.Printf("  processed image:resize   width=%d src=%s\n", p.Width, p.SrcURL)
		return nil
	})
	mux.HandleFunc("cleanup:tmp", func(ctx context.Context, t *asynq.Task) error {
		fmt.Println("  processed cleanup:tmp")
		return nil
	})
	mux.HandleFunc("billing:charge", func(ctx context.Context, t *asynq.Task) error {
		return fmt.Errorf("card declined") // demonstrates archive flow
	})
	if err := srv.Start(mux); err != nil {
		log.Fatal(err)
	}
	time.Sleep(3 * time.Second) // let the worker drain pending tasks
	srv.Shutdown()

	fmt.Println()
	fmt.Println("== 3. Inspector: real queue statistics ===========================")
	insp := asynq.NewInspector(opt)
	defer insp.Close()
	queues, err := insp.Queues()
	if err != nil {
		log.Fatal(err)
	}
	sort.Strings(queues)
	fmt.Printf("  %-10s %8s %9s %9s %8s %9s %10s\n",
		"queue", "size", "pending", "active", "sched", "archived", "processed")
	for _, q := range queues {
		qi, err := insp.GetQueueInfo(q)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("  %-10s %8d %9d %9d %8d %9d %10d\n",
			qi.Queue, qi.Size, qi.Pending, qi.Active, qi.Scheduled, qi.Archived, qi.Processed)
	}

	fmt.Println()
	fmt.Println("== 4. Archived task detail (retry exhausted) =====================")
	archived, err := insp.ListArchivedTasks("critical")
	if err != nil {
		log.Fatal(err)
	}
	for _, t := range archived {
		fmt.Printf("  id=%s type=%s last_err=%q retried=%d/%d\n",
			t.ID[:8], t.Type, t.LastErr, t.Retried, t.MaxRetry)
	}

	fmt.Println()
	fmt.Println("== 5. Scheduled task detail ======================================")
	scheduled, err := insp.ListScheduledTasks("low")
	if err != nil {
		log.Fatal(err)
	}
	for _, t := range scheduled {
		fmt.Printf("  id=%s type=%s next_process_at=%s\n",
			t.ID[:8], t.Type, t.NextProcessAt.Format(time.RFC3339))
	}
	fmt.Println()
	fmt.Println("demo seed complete: data remains in DB", demoDB, "for CLI / exporter inspection")
}

// flushDemoDB clears the demo DB via a throwaway client connection.
func flushDemoDB(opt asynq.RedisClientOpt) {
	c := opt.MakeRedisClient()
	type flusher interface {
		FlushDB(ctx context.Context) interface{ Err() error }
	}
	if f, ok := c.(flusher); ok {
		_ = f.FlushDB(context.Background()).Err()
	}
	if closer, ok := c.(interface{ Close() error }); ok {
		_ = closer.Close()
	}
}
